---
title: "The Knapsack Package"
author: "Jorge Villar Fuentes and Ashmaful Alam"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The package will contain three diﬀerent functions for solving what is called the knapsack problem:

- Brute Force Search
- Dynmic Programming
- Greedy Heuristic

To use this package you must have a data frame, with the variables v (value) and w (weight), and also a vector W with size 1 (maximum knapsack size)

To explain the three diferents forms to use this package, we use the same example, that is this:

    output: 
    set.seed(42)
    n <- 2000 
    knapsack_objects <- data.frame( 
    w=sample(1:4000, size = n, replace = TRUE), 
    v=runif(n = n, 0, 10000) 
    )

## Brute Force Search

    brute_force_knapsack()

The only solution that is guaranteed to give a correct answer in all situations for the knapsack problem is using brute-force search, i.e. going through all possible alternatives and return the maximum value found.

The function should check that the inputs are correct (i.e. a data.frame with two variables v and w) with only positive values.

Now we have an example:

    brute_force_knapsack(x = knapsack_objects[1:8,], W = 3500)

QUESTION:  How much time does it takes to run the algorithm for n = 16 objects?

    set.seed(42)
    n <- 16 
    knapsack_objects <- data.frame( 
    w=sample(1:4000, size = n, replace = TRUE), 
    v=runif(n = n, 0, 10000) 
    )
    system.time(knapsack_brute_force(x = knapsack_objects[1:8,], W = 3500))

   user  system elapsed 
   
   0.00    0.00    0.03 

## Dynamic Programming

    knapsack_dynamic()

If the weights are actually discrete values (as in our example) we can use this to create an algorithm that can solve the knapsack problem exact by iterating over all possible values of w.

Now we have an example:

    knapsack_dynamic(x = knapsack_objects[1:8,], W = 3500)

QUESTION: How much time does it takes to run the algorithm for n = 500 objects?

    set.seed(42)
    n <- 500 
    knapsack_objects <- data.frame( 
    w=sample(1:4000, size = n, replace = TRUE), 
    v=runif(n = n, 0, 10000) 
    )
    system.time(knapsack_dynamic(x = knapsack_objects[1:8,], W = 3500))

   user  system elapsed 
   
   0.06    0.00    0.13 

## Greedy Heuristic

    greedy_knapsack()

This algorithm will not give an exact result (but it can be shown that it will return at least 50% of the true maximum value), but it will reduce the computational complexity considerably (actually to O(nlogn) due to the sorting part of the algorithm).

Now we have an example:

    greedy_knapsack(x = knapsack_objects[1:800,], W = 3500)

QUESTION: How much time does it takes to run the algorithm for n = 1000000 objects?

    set.seed(42)
    n <- 1000000 
    knapsack_objects <- data.frame( 
    w=sample(1:4000, size = n, replace = TRUE), 
    v=runif(n = n, 0, 10000) 
    )
    system.time(greedy_knapsack(x = knapsack_objects[1:800,], W = 3500))

   user  system elapsed 
   
   0.03    0.01    0.06 

## Lineprof

QUESTION: What performance gain could you get by trying to improving your code?

to use this function we need this library:

    library(lineprof)
    
- Brute Force Knapsack with no parallel

    lineprof(brute_force_knapsack(x = knapsack_objects[1:8,], W = 3500, parallel=FALSE))

- Brute Force Knapsack with parallel

    lineprof(brute_force_knapsack(x = knapsack_objects[1:8,], W = 3500, parallel=TRUE))

- Knapsack Dynamic

    lineprof(knapsack_dynamic(x = knapsack_objects[1:8,], W = 3500))

- Greedy Heuristic

    lineprof(greedy_knapsack(x = knapsack_objects[1:800,], W = 3500))


